name: .NET CI/CD Test Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      # We tell it to look into the subfolder for the solution
      run: dotnet restore OrderSearchLibrary/OrderSearchLibrary.sln
      
    - name: Build
      run: dotnet build OrderSearchLibrary/OrderSearchLibrary.sln --no-restore
      
    - name: Test
      run: dotnet test OrderSearchLibrary/OrderSearchLibrary.sln --no-build --verbosity normal